jwt.secret=nESpy7bfl33jYbF7dJL/FwTZmnZkrcRZnxyq+4qfFAM=
spring.datasource.password=libpass123lib
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/test_db
spring.datasource.username=libraryuser
spring.jpa.hibernate.ddl-auto=update
spring.security.user.name=m
spring.security.user.password=root
server.port=8082
spring.application.name=expense-service
#eureka.client.service-url.defaultZone=${EUREKA_URL}